"""Encode Godot-rendered frames; artwork is generated by imagegen."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
paths = sorted((ROOT / "previews/head-pet-rendered").glob("*.png"))
if len(paths) != 80:
    raise SystemExit("Run export_head_pet_preview.gd first; expected 80 rendered frames.")
frames = [Image.open(path).convert("RGBA") for path in paths]
output = ROOT / "previews/cat-head-pet-v2.webp"
frames[0].save(output, save_all=True, append_images=frames[1:], duration=42,
               loop=0, lossless=True, method=4)
print(output)
